export const PRIMARY_BACKGROUND_COLOR = '#080708';
export const SECONDARY_BACKGROUND_COLOR = '#444444';
export const PRIMARY_FOREGROUND_COLOR = '#FCFCFC';
export const GREEN_ACCENT_COLOR = '#06D6A0';
export const YELLOW_ACCENT_COLOR = '#F2D0A9';

export const FONT_FAMILY = 'Lexend';