import axios from 'axios';
import * as fs from 'fs';
import { app, BrowserWindow, ipcMain } from 'electron';
import { PRIMARY_BACKGROUND_COLOR } from './constants/styleConstants';
import { FETCH_URL_EVENT_NAME, SAVE_TO_FILE_EVENT_NAME, APP_CLOSE_EVENT_NAME } from './constants/ipcConstants';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// Communication with renderer - certain tasks only the server can perform and not the renderer
ipcMain.handle(FETCH_URL_EVENT_NAME, async (event, ...args) => {
  console.log(`Received fetch URL event with URL ${args[0].url}`);
  const response = await axios.get(args[0].url);
  console.log(`Received response from Axios for URL ${args[0].url}`);
  return response.data;
})

ipcMain.handle(SAVE_TO_FILE_EVENT_NAME, async (event, ...args) => {
  console.log(`Received save to file event with filename ${args[0].filename}`);
  fs.writeFileSync(args[0].filename, args[0].content);
  console.log(`Successfully saved content to file ${args[0].filename}`);
})

// Create the window and invoke renderer
const createWindow = (): void => {
  const width = 850;
  const height = 600;

  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: height,
    width: width,
    minHeight: height,
    maxHeight: height,
    minWidth: width,
    maxWidth: width,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: true,
      contextIsolation: false
    },
    backgroundColor: PRIMARY_BACKGROUND_COLOR
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  // Register cleanup functions to window close.
  mainWindow.on('close', (event) => {
    console.log('Sending app close event');
    mainWindow.webContents.send(APP_CLOSE_EVENT_NAME);
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
